import assert from "node:assert/strict";
import { readFile, stat } from "node:fs/promises";
import test from "node:test";

test("build includes the playable game and worker entrypoint", async () => {
  const html = await readFile(new URL("../dist/client/index.html", import.meta.url), "utf8");
  const game = await readFile(new URL("../dist/client/game-v26.js", import.meta.url), "utf8");
  assert.match(html, /MSN球星大冒险/);
  assert.match(html, /音乐：世界杯荣耀曲/);
  assert.match(html, /1990 意大利·罗马斗兽场/);
  assert.match(html, /1994 美国·玫瑰碗/);
  assert.match(html, /1998 法国·巴黎铁塔/);
  assert.match(html, /2002 韩日·横滨港/);
  assert.match(html, /2006 德国·勃兰登堡门/);
  assert.match(html, /2010 南非·开普桌山/);
  assert.match(html, /2014 巴西·里约热内卢/);
  assert.match(html, /2018 俄罗斯·圣瓦西里/);
  assert.match(html, /2022 卡塔尔·多哈海滨/);
  assert.match(html, /2026 美加墨·联合盛典/);
  assert.doesNotMatch(html, /北美三国|北美3国/);
  assert.match(html, /no-cache, no-store, must-revalidate/);
  assert.match(html, /game-v26\.js/);
  assert.match(html, /id="restartButton"[^>]*>重玩本关<\/button>/);
  assert.match(html, /id="firstLevelButton"[^>]*>从第1关开始<\/button>/);
  assert.doesNotMatch(html, /game\.js\?v=/);
  assert.doesNotMatch(html, /举办地|游艇|冰川|绿茵场|幻想森林层|晴海沙滩层|极光雪山层/);
  for (const city of ["罗马", "帕萨迪纳", "巴黎", "首尔", "横滨", "柏林", "开普敦", "里约", "莫斯科", "多哈", "墨西哥城", "多伦多", "旧金山"]) {
    assert.match(game, new RegExp(city));
  }
  assert.match(game, /drawRoundedRect\(18, 17, 560, 78/);
  assert.match(game, /关卡进度/);
  assert.match(game, /ctx\.textAlign = "center"; ctx\.textBaseline = "middle"/);
  assert.match(game, /trioBoxX \+ trioBoxW \/ 2/);
  assert.match(game, /trophyBoxX \+ trophyBoxW \/ 2/);
  assert.equal([...game.matchAll(/level\.scene ===/g)].length, 10);
  assert.equal([...game.matchAll(/routes: \{ main:/g)].length, 10);
  assert.doesNotMatch(game, /举办地历史街区|举办地城市广场|幻想森林层|晴海沙滩层|极光雪山层/);
  assert.match(html, /世界杯金靴套装/);
  assert.match(html, /世界杯冠军奖牌/);
  assert.match(html, /内马尔“帅”字队长袖标/);
  assert.match(html, /世界杯闪电护腿/);
  assert.match(html, /世界杯门神手套/);
  assert.doesNotMatch(html, /潮流头巾|反戴潮帽|美国队长|蜘蛛侠|绿巨人/);
  assert.doesNotMatch(html, /musicSelect|Dai Dai|火影|海贼王/);
  assert.match(html, /1000分＋6城苏亚雷斯加入并换巴萨战袍/);
  assert.match(game, /BARCA_CHARACTER_IMAGES/);
  assert.match(game, /barcaNumber: 11/);
  assert.match(game, /msnStage === 3 \? "barca"/);
  assert.match(game, /巴萨MSN合捧欧冠大耳朵杯/);
  assert.match(game, /function drawChampionsLeagueTrophy/);
  assert.match(game, /two oversized open handles/);
  assert.doesNotMatch(game, /drawWorldCupTrophy|巴萨MSN合捧大力神杯/);
  assert.match(game, /世界杯助威围巾/);
  assert.match(game, /世界杯能量球/);
  assert.match(game, /prize\.type = "scarf"/);
  assert.match(game, /type: "matchball"/);
  assert.doesNotMatch(game, /彩虹奖励|红蘑菇|type: "rainbow"|type: "mushroom"/);
  assert.match(html, /500分＋3城梅西加入/);
  assert.match(html, /1000分＋6城苏亚雷斯加入/);
  assert.match(html, /第7—9枚城市印章获得欧冠奖杯碎片/);
  assert.match(html, /巴萨MSN合捧大耳朵杯/);
  assert.match(html, /城市印章：<strong id="stampCount">0 \/ 10<\/strong>/);
  assert.match(game, /hat-adventure-city-stamps/);
  assert.match(game, /progressScore >= 1000 && stamps >= 6/);
  assert.match(game, /progressScore >= 500 && stamps >= 3/);
  assert.match(game, /function hasChampionsLeagueTrophy/);
  assert.match(game, /journeyLevels\.size >= LEVELS\.length/);
  assert.match(game, /const stamps = journeyLevels\.size/);
  assert.match(game, /function journeyScore\(score = totalCoins \+ coins\) \{\s+return score;/);
  assert.doesNotMatch(game, /return Math\.max\(bestScore, score\)/);
  assert.match(game, /function restartCurrentLevel/);
  assert.match(game, /function restartFromFirstLevel/);
  assert.match(game, /document\.querySelector\("#firstLevelButton"\)\.addEventListener\("click", restartFromFirstLevel\)/);
  assert.match(game, /journeyLevels = new Set\(\)/);
  assert.match(game, /card\.milestone && completedLevels\.size >= card\.cities/);
  assert.match(game, /function updateLevelOptionProgress/);
  assert.match(game, /const NEYMAR_CELEBRATIONS/);
  for (const taunt of ["SIU！", "禅意模式", "抱臂定格", "滑跪指天", "桑巴舞步", "伯纳乌展翼", "队长滑跪"]) {
    assert.match(game, new RegExp(taunt));
  }
  assert.match(game, /player\.celebrationTimer > 0/);
  assert.match(game, /function startNeymarCelebration/);
  assert.match(game, /function playCelebrationSound/);
  assert.doesNotMatch(game, /enemy\.tauntTimer|completeEnemyTaunt|drawTauntEffects/);
  assert.match(game, /const CELEBRATION_EMOTE_IMAGES/);
  assert.match(game, /function drawCelebrationEmote/);
  assert.match(game, /CELEBRATION_EMOTE_IMAGES\[type\]/);
  assert.match(game, /姆巴佩抱臂表情已在内马尔头顶弹出/);
  assert.match(game, /登贝莱滑跪表情已在内马尔头顶弹出/);
  assert.doesNotMatch(game, /growPlayer\(|内马尔公仔变大了|登贝莱奖励/);
  assert.doesNotMatch(game, /fillText\("✊"|const skin = "#c98b62"/);
  assert.match(game, /showFootballReward\("SIU！", "C罗庆祝表情已在内马尔头顶弹出/);
  assert.doesNotMatch(game, /C罗奖励|C罗掉落/);
  assert.match(html, /内马尔头顶弹出其专属庆祝表情包/);
  assert.doesNotMatch(html, /登贝莱变大/);
  assert.match(game, /player\.heroForm = "black"/);
  assert.match(game, /activeForm === "black" \? "black" : \(msnStage === 3 \? "barca"/);
  assert.match(game, /桑巴庆祝表情弹出，内马尔变为暗影公仔；MSN巴萨球衣状态下也会生效/);
  assert.match(html, /内马尔头顶会弹出其专属庆祝表情包/);
  await stat(new URL("../dist/client/game-v26.js", import.meta.url));
  await stat(new URL("../dist/client/assets/characters/neymar-barca.png", import.meta.url));
  await stat(new URL("../dist/client/assets/characters/messi-barca.png", import.meta.url));
  await stat(new URL("../dist/client/assets/characters/suarez-barca.png", import.meta.url));
  for (const id of ["ronaldo", "haaland", "mbappe", "dembele", "vinicius", "bellingham", "kane"]) {
    await stat(new URL(`../dist/client/assets/characters/emotes/${id}-celebration.png`, import.meta.url));
  }
  await stat(new URL("../dist/client/world-cup-stadium.wav", import.meta.url));
  const worker = await readFile(new URL("../dist/server/index.js", import.meta.url), "utf8");
  assert.match(worker, /CDN-Cache-Control/);
  assert.match(worker, /no-cache, no-store, must-revalidate/);
});
